all:
	gcc player.c -std=gnu99 -o player
	gcc bidding_system.c -std=gnu99 -o bidding_system
	gcc host.c -std=gnu99 -o host
	gcc player_bonus.c -std=gnu99 -o player_bonus

clean:
	rm player
	rm bidding_system
	rm host
	rm player_bonus

