all:
	gcc bidding_system.c -std=gnu99 -o bidding_system
	gcc customer.c -std=gnu99 -o customer
	gcc bidding_system_EDF.c -std=gnu99 -o bidding_system_EDF
clean:
	rm bidding_system
	rm customer
	rm bidding_system_EDF
see:
	cat bidding_system_log
	cat customer_log
